# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('send_type', models.CharField(max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2017, 9, 26, 6, 0, 49, 33401, tzinfo=utc))),
            ],
            options={
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
            },
        ),
    ]
