# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_auto_20170921_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 21, 10, 23, 0, 746969), verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
    ]
