# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_auto_20170921_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_time',
        ),
    ]
